In [1]:
import pandas as pd
from sklearn import svm,metrics
from sklearn.model_selection import train_test_split

In [2]:
csv = pd.read_csv('iris.csv')
csv

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
csv_data = csv[['SepalLength','SepalWidth','PetalLength','PetalWidth']]
csv_data

     SepalLength  SepalWidth  PetalLength  PetalWidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [4]:
csv_label = csv['Name']
csv_label

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Name, Length: 150, dtype: object

In [5]:
#학습 전용 데이터와 테스트 전용 데이터로 나누기
train_data,test_data,train_label,test_label = train_test_split(csv_data,csv_label)

In [6]:
train_data

     SepalLength  SepalWidth  PetalLength  PetalWidth
116          6.5         3.0          5.5         1.8
137          6.4         3.1          5.5         1.8
115          6.4         3.2          5.3         2.3
106          4.9         2.5          4.5         1.7
37           4.9         3.1          1.5         0.1
..           ...         ...          ...         ...
147          6.5         3.0          5.2         2.0
49           5.0         3.3          1.4         0.2
84           5.4         3.0          4.5         1.5
131          7.9         3.8          6.4         2.0
0            5.1         3.5          1.4         0.2

[112 rows x 4 columns]

In [7]:
test_data

     SepalLength  SepalWidth  PetalLength  PetalWidth
79           5.7         2.6          3.5         1.0
12           4.8         3.0          1.4         0.1
67           5.8         2.7          4.1         1.0
98           5.1         2.5          3.0         1.1
121          5.6         2.8          4.9         2.0
82           5.8         2.7          3.9         1.2
101          5.8         2.7          5.1         1.9
148          6.2         3.4          5.4         2.3
119          6.0         2.2          5.0         1.5
75           6.6         3.0          4.4         1.4
27           5.2         3.5          1.5         0.2
78           6.0         2.9          4.5         1.5
38           4.4         3.0          1.3         0.2
11           4.8         3.4          1.6         0.2
113          5.7         2.5          5.0         2.0
90           5.5         2.6          4.4         1.2
139          6.9         3.1          5.4         2.1
34           4.9         3.1          1.5         0.1
146          6.3         2.5          5.0         1.9
5            5.4         3.9          1.7         0.4
42           4.4         3.2          1.3         0.2
140          6.7         3.1          5.6         2.4
97           6.2         2.9          4.3         1.3
1            4.9         3.0          1.4         0.2
35           5.0         3.2          1.2         0.2
18           5.7         3.8          1.7         0.3
108          6.7         2.5          5.8         1.8
85           6.0         3.4          4.5         1.6
44           5.1         3.8          1.9         0.4
127          6.1         3.0          4.9         1.8
118          7.7         2.6          6.9         2.3
96           5.7         2.9          4.2         1.3
15           5.7         4.4          1.5         0.4
59           5.2         2.7          3.9         1.4
40           5.0         3.5          1.3         0.3
142          5.8         2.7          5.1         1.9
10           5.4         3.7          1.5         0.2
138          6.0         3.0          4.8         1.8

In [8]:
#학습
clf = svm.SVC()
clf.fit(train_data,train_label)

SVC()

In [9]:
pre = clf.predict(test_data)

In [11]:
ac_score = metrics.accuracy_score(test_label,pre)

In [12]:
pre

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor'], dtype=object)

In [13]:
test_label

79     Iris-versicolor
12         Iris-setosa
67     Iris-versicolor
98     Iris-versicolor
121     Iris-virginica
82     Iris-versicolor
101     Iris-virginica
148     Iris-virginica
119     Iris-virginica
75     Iris-versicolor
27         Iris-setosa
78     Iris-versicolor
38         Iris-setosa
11         Iris-setosa
113     Iris-virginica
90     Iris-versicolor
139     Iris-virginica
34         Iris-setosa
146     Iris-virginica
5          Iris-setosa
42         Iris-setosa
140     Iris-virginica
97     Iris-versicolor
1          Iris-setosa
35         Iris-setosa
18         Iris-setosa
108     Iris-virginica
85     Iris-versicolor
44         Iris-setosa
127     Iris-virginica
118     Iris-virginica
96     Iris-versicolor
15         Iris-setosa
59     Iris-versicolor
40         Iris-setosa
142     Iris-virginica
10         Iris-setosa
138     Iris-virginica
Name: Name, dtype: object

In [14]:
ac_score = metrics.accuracy_score(test_label,pre)
print('정답률 :',ac_score)

정답률 : 0.9210526315789473