In [1]:
from haversine import haversine
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np
import pandas as pd

In [4]:
df = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='가축전염병(기존자료)_발생일자별')
df.head()

,발생일자,가축전염병명,국가,광역시도,시군구,읍면동,리,읍면동 상세,축종,발생두수(마리),종식일,위도,경도,관측지코드
0,2019-01-04,가금티프스,대한민국,전라북도,부안군,보안면,남포리,전라북도 부안군 보안면 남포리,닭,19000,NaN,35.631876,126.661607,74
1,2019-01-04,가금티프스,대한민국,충청남도,당진시,신평면,금천리,충청남도 당진시 신평면 금천리,닭,5600,NaN,36.891324,126.773754,89
2,2019-01-04,가금티프스,대한민국,전라북도,부안군,보안면,상입석리,전라북도 부안군 보안면 상입석리,닭,1934,NaN,35.626821,126.678355,74
3,2019-01-10,돼지생식기호흡기증후군,대한민국,전라북도,남원시,내척동,NaN,전라북도 남원시 내척동,돼지,5,NaN,35.440464,127.359133,73
4,2019-01-25,가금티프스,대한민국,전라북도,순창군,적성면,괴정리,전라북도 순창군 적성면 괴정리,닭,12100,NaN,35.413096,127.234357,75

In [5]:
df1 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='가축전염병(국가방역시스템)_일자별')
df1.head()

         발생일자       가축전염병명     농장명                농장소재지  축종   발생두수
0  2019-01-01        가금티푸스    선들농장    전라북도 부안군 보안면 상입석리   닭   1934
1  2019-01-07  돼지생식기호흡기증후군      확인         전라북도 남원시 내척동  돼지      5
2  2019-01-08        가금티푸스    남도축산     전라북도 김제시 용지면 신정리   닭  43000
3  2019-01-23        가금티푸스     정윤섭     전라북도 순창군 적성면 괴정리   닭  12100
4  2019-03-07  돼지생식기호흡기증후군  창진영농조합  제주특별자치도 제주시 한림읍 상대리  돼지      2

In [6]:
df2 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='가축전염병(국가방역시스템)_월별통계')
df2.head()

        년월    국가   광역시도 축종  농가수  발생두수
0  2019-01  대한민국  서울특별시  닭    0     0
1  2019-01  대한민국  부산광역시  닭    0     0
2  2019-01  대한민국  대구광역시  닭    0     0
3  2019-01  대한민국  인천광역시  닭    0     0
4  2019-01  대한민국  광주광역시  닭    0     0

In [7]:
df3 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='가축사육시설')
df3.head()

,년도,국가,광역시도,시군구,읍면동,읍면동 상세,축종,업체수,경영형태_자영,경영형태_임차,사육 규모,위도,경도,관측지코드
0,2019,대한민국,강원도,강릉시,옥계면,강원도 강릉시 옥계면,닭,6,5,1,3825,37.612663,129.037931,2
1,2019,대한민국,강원도,강릉시,강동면,강원도 강릉시 강동면,닭,30,21,9,534530,37.728094,128.954226,0
2,2019,대한민국,강원도,강릉시,구정면,강원도 강릉시 구정면,닭,22,22,0,417340,37.718376,128.880054,0
3,2019,대한민국,강원도,강릉시,운산동,강원도 강릉시 운산동,닭,1,1,0,200,37.726767,128.933345,0
4,2019,대한민국,강원도,강릉시,장현동,강원도 강릉시 장현동,닭,3,3,0,12000,37.729016,128.894455,0

In [8]:
df4 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='조류서식지')
df4.head()

,년월,국가,광역시도,시군구,서식지명,개체수,위도,경도,관측지코드
0,2019-01,대한민국,경상북도,구미시,구미 해평(도흥리-일선교),17392,36.272936,128.339902,34
1,2019-01,대한민국,경상북도,김천시,감천,1041,36.001578,128.034656,93
2,2019-01,대한민국,경상북도,안동시,낙동강(일선교-안동시),1878,36.554260,128.735834,38
3,2019-01,대한민국,경상북도,예천군,내성천,91,36.793139,128.700527,40
4,2019-01,대한민국,경상북도,안동시,안동호,1922,36.635762,128.847894,38

In [9]:
df5 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='조류폐사체')
df5.head()

,시료채취일자,국가,광역시도,시군구,읍면동,읍면동 상세,개체구분,위도,경도,관측지코드
0,2021-01-01,대한민국,경상남도,창원시 의창구,대산면,경상남도 창원시 의창구 대산면,폐사체,35.315752,128.680597,24
1,2021-01-08,대한민국,경상남도,창원시 의창구,동읍,경상남도 창원시 의창구 동읍,폐사체,35.310149,128.668833,24
2,2021-01-09,대한민국,경상북도,구미시,지산동,경상북도 구미시 지산동,폐사체,36.132744,128.355170,34
3,2021-01-11,대한민국,제주특별자치도,제주시,구좌읍,제주특별자치도 제주시 구좌읍,분변,33.505418,126.891848,82
4,2021-01-11,대한민국,경상남도,거창군,거창읍,경상남도 거창군 거창읍,폐사체,35.694956,127.910711,20

In [10]:
df6 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='멧돼지폐사체')
df6.head()

,발견일자,국가,광역시도,시군구,읍면동,읍면동 상세,개체구분,위도,경도,관측지코드
0,2019-10-02,대한민국,경기도,연천군,신서면,경기도 연천군 신서면,폐사체,38.264123,127.077756,10
1,2019-10-11,대한민국,강원도,철원군,원남면,강원도 철원군 원남면,폐사체,38.303126,127.600284,10
2,2019-10-12,대한민국,강원도,철원군,원남면,강원도 철원군 원남면,폐사체,38.309478,127.602335,10
3,2019-10-12,대한민국,강원도,철원군,원남면,강원도 철원군 원남면,폐사체,38.310692,127.604746,10
4,2019-10-14,대한민국,경기도,연천군,장남면,경기도 연천군 장남면,폐사체,37.997654,126.868309,18

In [11]:
df7 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='멧돼지서식지')
df7.head()

,년도,국가,광역시도,시군구,읍면동 상세,면적(ha),멧돼지-밀도(1/100ha),개체수,축종,위도,경도,관측지코드
0,2019,대한민국,경기도,가평군,경기도 가평군,84358.18886,4.7,3965,멧돼지,37.831540,127.509883,11
1,2019,대한민국,경기도,광주시,경기도 광주시,43098.85897,3.3,1422,멧돼지,37.417141,127.256141,16
2,2019,대한민국,경기도,남양주시,경기도 남양주시,45814.42138,10.0,4581,멧돼지,37.636003,127.216528,51
3,2019,대한민국,경기도,양평군,경기도 양평군,87778.96965,2.9,2546,멧돼지,37.491219,127.487561,16
4,2019,대한민국,경기도,포천시,경기도 포천시,82698.64351,4.7,3887,멧돼지,37.894915,127.200355,14

In [12]:
df8 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='기상관측(월별)')
df8.head()

,년월,국가,광역시도,지점명,위도,경도,관측지코드,기온,최저기온,최고기온,강수량
0,2019-01,대한민국,강원도,강릉,37.7515,128.891,0,2.832258,-1.112903,7.664516,0.535484
1,2019-02,대한민국,강원도,강릉,37.7515,128.891,0,3.750000,-0.150000,8.217857,0.632143
2,2019-03,대한민국,강원도,강릉,37.7515,128.891,0,8.909677,4.425806,13.841935,1.600000
3,2019-04,대한민국,강원도,강릉,37.7515,128.891,0,12.560000,7.480000,17.130000,2.850000
4,2019-05,대한민국,강원도,강릉,37.7515,128.891,0,20.983871,15.841935,26.229032,0.145161

In [14]:
df9 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='기상관측(일별)_결측치제거')
df9.head()

           일자    국가 광역시도 지점명       위도       경도  관측지코드   기온  최저기온  최고기온  강수량
0  2019-01-01  대한민국  강원도  강릉  37.7515  128.891      0 -0.7  -2.7   2.9  0.0
1  2019-01-02  대한민국  강원도  강릉  37.7515  128.891      0  0.0  -3.4   6.3  0.0
2  2019-01-03  대한민국  강원도  강릉  37.7515  128.891      0  1.2  -3.2   6.8  0.0
3  2019-01-04  대한민국  강원도  강릉  37.7515  128.891      0  3.8   0.2   8.4  0.0
4  2019-01-05  대한민국  강원도  강릉  37.7515  128.891      0  1.9  -1.2   5.1  0.0

In [15]:
df10 = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='관측지코드')
df10.head()

    지점       위도        경도  관측지코드
0   강릉  37.7515  128.8910      0
1  대관령  37.6771  128.7183      1
2   동해  37.5071  129.1243      2
3  북강릉  37.8046  128.8554      3
4  북춘천  37.9474  127.7544      4