In [8]:
import requests
import pprint
import json

In [9]:
import pandas as pd
from datetime import datetime
from pandas import json_normalize

In [23]:
address_df = pd.read_csv('주소.csv', encoding='utf8')
address_df['리'] = address_df['리'].fillna('')
address_df

         도  시군구   읍면동    리
0     충청남도  홍성군   홍북면  내덕리
1    대구광역시  달성군   유가면   음리
2    대구광역시  달성군   옥포면
3     충청북도  청원군   강외면  동평리
4     경상남도  김해시   장유면  내덕리
..     ...  ...   ...  ...
125   경상북도  경산시   압량읍  강서리
126   경상북도  구미시   산동읍  임천리
127   충청북도  진천군   덕산읍  인산리
128   경상북도  구미시   산동읍  백현리
129    강원도  홍천군  영귀미면  월운리

[130 rows x 4 columns]

In [36]:
user_key = '00170112-DCDA-3D9C-BCEA-FD32C805A371'
domain = 'localhost'

list = []

for address in address_df.loc[:,'리']:

    # 읍면동 주소 요청
    # api_url = 'https://api.vworld.kr/req/data?service=data&request=GetFeature&data=LT_C_ADEMD_INFO&key='+user_key+'&domain='+domain+'&attrFilter=full_nm:=:'+address
    
    # 리주소 요청
    api_url = 'http://api.vworld.kr/req/data?service=data&request=GetFeature&data=LT_C_ADRI_INFO&key='+user_key+'&domain='+domain+'&attrFilter=li_kor_nm:=:'+address

    # url 불러오기
    response = requests.get(api_url)

    #데이터 값 출력해보기
    contents = response.text

    #문자열을 json으로 변경
    json_ob = json.loads(contents)
    
    if json_ob['response']['status'] =='OK':
        latitude = json_ob['response']['result']['featureCollection']['bbox'][1]
        longitude = json_ob['response']['result']['featureCollection']['bbox'][0]
        list.append([address, latitude, longitude])
    else:
        list.append([address, ' ', ' '])
    
result = pd.DataFrame(list)
result

       0          1           2
0    내덕리  36.614235  126.675079
1     음리  35.690078  128.474798
2
3    동평리  36.259976  127.231317
4    내덕리  36.614235  126.675079
..   ...        ...         ...
125  강서리  35.820409  126.925912
126  임천리  34.593508  126.733162
127  인산리  35.525013  126.391865
128  백현리  36.175564  127.352998
129  월운리  35.057803  127.865729

[130 rows x 3 columns]

In [39]:
result.to_csv('주소 위경도.csv', encoding='CP949')