In [10]:
from haversine import haversine
import warnings
warnings.filterwarnings(action='ignore')
import numpy as np
import pandas as pd

In [20]:
df = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='Sheet1')
df

,년월일,감염병명,축사명,주소,위도,경도,품종,발생두수
0,2019-01-01,가금티푸스,선들농장,전라북도 부안군 보안면 상입석리,35.626821,126.678355,닭,1934
1,2019-01-08,가금티푸스,남도축산,전라북도 김제시 용지면 신정리,35.843882,126.975635,닭,43000
2,2019-01-23,가금티푸스,정윤섭,전라북도 순창군 적성면 괴정리,35.413096,127.234357,닭,12100
3,2019-04-13,가금티푸스,박성근,경상남도 함안군 함안면 파수리,35.223439,128.401233,닭,5
4,2019-04-21,가금티푸스,학산농장,전라남도 영암군 학산면 용산리,34.735725,126.631893,닭,300
...,...,...,...,...,...,...,...,...
114,2021-12-14,고병원성조류인플루엔자,푸른초원농원,충청남도 아산시 음봉면 산정리,36.855795,127.003539,닭,-
115,2021-12-16,고병원성조류인플루엔자,보성3농장,세종특별자치시 연동면 문주리,36.551285,127.307688,닭,-
116,2021-12-20,고병원성조류인플루엔자,현대농장,전라남도 영암군 시종면 신학리,34.826911,126.573289,닭,-
117,2021-12-23,고병원성조류인플루엔자,영광농장,세종특별자치시 부강면 등곡리,36.513104,127.391671,닭,-
118,2021-12-24,가금티푸스,성웅농장,경기도 양평군 양동면 쌍학리,37.412233,127.748239,닭,520

In [21]:
# country 컬럼을 선택합니다.
# 컬럼의 값과 조건을 비교합니다.
# 그 결과를 새로운 변수에 할당합니다.
chicken = df['품종'] == '닭'
# 사육개체수과 감염개체수
# 조건를 충족하는 데이터를 필터링하여 새로운 변수에 저장합니다.
dfc = df[chicken]

# 결과를 출력합니다.
dfc

# # dfcc = dfc.iloc[:,0:7]
# # dfccc = dfc.iloc[:,7:8]
# dfcc = dfc[['발생두수(마리)']]
# # dfccccc = dfc.iloc[:,14:17]
# # dfcccccc = dfc.iloc[:,19:23]
# # dfcc = pd.concat([dfccccc,dfcccccc],axis=1)
# dfcc.head()

,년월일,감염병명,축사명,주소,위도,경도,품종,발생두수
0,2019-01-01,가금티푸스,선들농장,전라북도 부안군 보안면 상입석리,35.626821,126.678355,닭,1934
1,2019-01-08,가금티푸스,남도축산,전라북도 김제시 용지면 신정리,35.843882,126.975635,닭,43000
2,2019-01-23,가금티푸스,정윤섭,전라북도 순창군 적성면 괴정리,35.413096,127.234357,닭,12100
3,2019-04-13,가금티푸스,박성근,경상남도 함안군 함안면 파수리,35.223439,128.401233,닭,5
4,2019-04-21,가금티푸스,학산농장,전라남도 영암군 학산면 용산리,34.735725,126.631893,닭,300
...,...,...,...,...,...,...,...,...
114,2021-12-14,고병원성조류인플루엔자,푸른초원농원,충청남도 아산시 음봉면 산정리,36.855795,127.003539,닭,-
115,2021-12-16,고병원성조류인플루엔자,보성3농장,세종특별자치시 연동면 문주리,36.551285,127.307688,닭,-
116,2021-12-20,고병원성조류인플루엔자,현대농장,전라남도 영암군 시종면 신학리,34.826911,126.573289,닭,-
117,2021-12-23,고병원성조류인플루엔자,영광농장,세종특별자치시 부강면 등곡리,36.513104,127.391671,닭,-
118,2021-12-24,가금티푸스,성웅농장,경기도 양평군 양동면 쌍학리,37.412233,127.748239,닭,520

In [22]:
dead = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='조류폐사체')
dead.head()

,시료채취일자,국가,광역시도,시군구,읍면동,읍면동 상세,개체구분,위도,경도,관측지코드
0,2021-01-01,대한민국,경상남도,창원시 의창구,대산면,경상남도 창원시 의창구 대산면,폐사체,35.315752,128.680597,24
1,2021-01-08,대한민국,경상남도,창원시 의창구,동읍,경상남도 창원시 의창구 동읍,폐사체,35.310149,128.668833,24
2,2021-01-09,대한민국,경상북도,구미시,지산동,경상북도 구미시 지산동,폐사체,36.132744,128.355170,34
3,2021-01-11,대한민국,제주특별자치도,제주시,구좌읍,제주특별자치도 제주시 구좌읍,분변,33.505418,126.891848,82
4,2021-01-11,대한민국,경상남도,거창군,거창읍,경상남도 거창군 거창읍,폐사체,35.694956,127.910711,20

In [6]:
result = pd.DataFrame(columns=['발생일자(가)','가축전염병명(가)','농장명(가)','농장소재지(가)','위도(가)','경도(가)','축종(가)','발생두수(가)','시료채취일자(가)','국가(가)','광역시도(가)','시군구(가)','읍면동(가)','읍면동 상세(가)','개체구분(가)','위도(가)','경도(가)','관측지코드(가)'])
listc = []
aa = 0
for c in range(len(dfc)):
    dfcr = dfc.loc[c]
    la = float(dfcr['위도'])
    lo = float(dfcr['경도'])
    chicken = (la,lo)  
    for a in range(len(dead)):
        deadr = dead.loc[a]
        laa = float(deadr['위도'])
        loa = float(deadr['경도'])
        ai = (laa,loa)
        # 거리 계산
        listc.append(haversine(chicken, ai, unit = 'km'))
        dfcli = dfcc.loc[c].to_list()
        dfali = dfaa.loc[a].to_list()
        dfdf = dfcli + dfali
        c = c+1
        bb = aa*cc
        i=bb-1
        result.loc[i]=dfdf
result

          감염개체수
0         19000
1         19000
2         19000
3         19000
4         19000
...         ...
41111443    520
41111564    520
41111685    520
41111806    520
41111927    520

[339768 rows x 1 columns]

In [12]:
living = pd.read_excel('가축전염병 통합데이터_220902_v1.xlsx',sheet_name='조류서식지')
living.head()

,년월,국가,광역시도,시군구,서식지명,개체수,위도,경도,관측지코드
0,2019-01,대한민국,경상북도,구미시,구미 해평(도흥리-일선교),17392,36.272936,128.339902,34
1,2019-01,대한민국,경상북도,김천시,감천,1041,36.001578,128.034656,93
2,2019-01,대한민국,경상북도,안동시,낙동강(일선교-안동시),1878,36.554260,128.735834,38
3,2019-01,대한민국,경상북도,예천군,내성천,91,36.793139,128.700527,40
4,2019-01,대한민국,경상북도,안동시,안동호,1922,36.635762,128.847894,38

In [16]:
print(len(dfc))
print(len(dead))

119
229

In [6]:
# aa = 0
# for c in range(121):
#     cc = c+1    
#     for a in range(300):
#         aa = aa+1
#         bb = aa*cc
#         i=bb-1
#         print(cc,aa,i)

In [8]:
result['거리(KM)'] = listc
result

,발생일자(가),가축전염병명(가),광역시도(가),시군구(가),읍면동(가),리(가),위도(가),경도(가),관측지코드,관측지일자코드,...,일교차,일강수량,평균풍속,최다풍향,해당년월(서),시도(서),시군(서),위도(서),경도(서),거리(KM)
0,2019-01-04,가금티프스,전라북도,부안군,보안면,남포리,35.631876,126.661607,74,74-20190104,...,11.0,0.0,0.5,20.0,Oct-17,경기도,연천군,38.096400,127.074600,276.493866
1,2019-01-04,가금티프스,전라북도,부안군,보안면,남포리,35.631876,126.661607,74,74-20190104,...,11.0,0.0,0.5,20.0,Nov-17,경기도,연천군,38.096400,127.074600,276.493866
2,2019-01-04,가금티프스,전라북도,부안군,보안면,남포리,35.631876,126.661607,74,74-20190104,...,11.0,0.0,0.5,20.0,Dec-17,경기도,연천군,38.096400,127.074600,276.493866
3,2019-01-04,가금티프스,전라북도,부안군,보안면,남포리,35.631876,126.661607,74,74-20190104,...,11.0,0.0,0.5,20.0,Jan-18,경기도,연천군,38.096400,127.074600,276.493866
4,2019-01-04,가금티프스,전라북도,부안군,보안면,남포리,35.631876,126.661607,74,74-20190104,...,11.0,0.0,0.5,20.0,Feb-18,경기도,연천군,38.096400,127.074600,276.493866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41111443,2021-12-29,가금티프스,경기도,양평군,양동면,쌍학리,37.412233,127.748239,7,7-20211229,...,9.8,0.0,1.0,250.0,21-Nov,경상북도,울진-원덕 해안,37.148708,129.362286,145.777349
41111564,2021-12-29,가금티프스,경기도,양평군,양동면,쌍학리,37.412233,127.748239,7,7-20211229,...,9.8,0.0,1.0,250.0,21-Dec,경상북도,울진-원덕 해안,37.148708,129.362286,145.777349
41111685,2021-12-29,가금티프스,경기도,양평군,양동면,쌍학리,37.412233,127.748239,7,7-20211229,...,9.8,0.0,1.0,250.0,22-Jan,경상북도,울진-원덕 해안,37.148708,129.362286,145.777349
41111806,2021-12-29,가금티프스,경기도,양평군,양동면,쌍학리,37.412233,127.748239,7,7-20211229,...,9.8,0.0,1.0,250.0,22-Feb,경상북도,울진-원덕 해안,37.148708,129.362286,145.777349
41111927,2021-12-29,가금티프스,경기도,양평군,양동면,쌍학리,37.412233,127.748239,7,7-20211229,...,9.8,0.0,1.0,250.0,22-Mar,경상북도,울진-원덕 해안,37.148708,129.362286,145.777349

In [7]:
result.to_excel('발생 두수만 뽑음.xlsx')

In [10]:
# # result = pd.concat([dfcc,dfaa],axis=1)
# # result.head()
# dfccr = dfcc.iloc[1]
# # # # print(type(dfccr))
# # # dfccr
# # dfcli = dfcc.loc[0].to_list()
# # dfali = dfaa.loc[0].to_list()
# # dfdf = dfcli + dfali
# # result.loc[0] = dfdf
# # result
# # result['거리(KM)'] = listc
# # a=0
# # c=1
# # cc = c+1
# # aa = a+1
# # i = cc*aa-1
# # i
# df_dict = dfccr.to_dict()
# df_dict
# result = pd.DataFrame(columns=['발생일자(가)','가축전염병명(가)','광역시도(가)','시군구(가)','읍면동(가)','리(가)','위도(가)','경도(가)','시료채취일자(야)','시도(야)','시군(야)','주소(야)','시료(야)','위도(야)','경도(야)'])
# result = pd.DataFrame()
# dfccr = dfcc.loc[1]
# dfaar = dfaa.loc[1]
# dfcdic = dfccr.values.to_dict()
# dfadic = dfaar.to_dict()
# dfdf = dict(dfcdic, **dfadic)
# result = result.append(dfdf, ignore_index = True)
# result